routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\ExportController;
use App\Http\Controllers\FilterExcelController;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\ProfilController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RegisterController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect('/produk');
});

    Route::get('login', [AuthController::class, 'index'])->name('login');
    Route::post('auth', [AuthController::class, 'login']);
    Route::get('register', [RegisterController::class, 'index'])->name('register');
    Route::post('register/process',[RegisterController::class, 'register']);

Route::middleware(['auth'])->group(function (){
    Route::post('logout', [AuthController::class, 'logout']);
    Route::resource('produk', ProdukController::class);
    Route::resource('profile', ProfileController::class);  
    Route::get('download', [ExportController::class, 'export'])->name('export');
    Route::get('excel', [FilterExcelController::class, 'index']);
});

Route::get('storage', function () {
    Artisan::call('storage:link');
    return 'success';
});

app/Models/Produk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    use HasFactory;
    protected $table = 'produk';
    protected $guarded = ['id'];

    public function kategori(){
        return $this->belongsTo(Kategori::class);
    }
}

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;

use App\Exports\ExportProduk;
use App\Models\Kategori;
use App\Models\Produk;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Maatwebsite\Excel\Facades\Excel;
use Symfony\Component\HttpKernel\HttpCache\Store;

class ProdukController extends Controller
{
    public function index(Request $request)
    {
        $cariKategori = $request->kategori;
        $cariProduk = $request->cari_produk;
        $kategori = Kategori::all();
        $queryProduk = Produk::query();
        if ($cariKategori) {
            $queryProduk->where('kategori_id',$cariKategori);
        }
        if ($cariProduk) {
            $queryProduk->where('nama_produk',$cariProduk);
        }
        $produk = $queryProduk->paginate(10);
        return view('produk.index', compact('kategori', 'produk'));
    }
    public function data(){
        $item = Produk::paginate(10);
        return view('produk.table', compact('item'));
    }
    public function create()
    {
        $kategori = Kategori::all();
        return view('produk.create', compact('kategori'));
    }
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'kategori'=>'required',
            'nama_produk'=>'required|unique:produk,nama_produk',
            'harga_beli'=>'required|numeric',
            'stok'=>'required|numeric',
            'file' => 'required|file|mimes:jpeg,png|max:100',
        ]);
        $path = $request->file('file')->store('foto_produk');
        $harga_beli = $request->harga_beli;
        $harga_jual = $harga_beli + ($harga_beli * 0.3);

        $produk = new Produk;
        $produk->nama_produk = $request->nama_produk;
        $produk->kategori_id = $request->kategori;
        $produk->harga_beli = $request->harga_beli;
        $produk->harga_jual = $harga_jual;
        $produk->stok = $request->stok;
        $produk->image = $path;
        $produk->save();

        return redirect('produk')->with('success','Produk berhasil ditambah');
    }

    public function edit(string $id)
    {
        $produk = Produk::where('id',$id)->get();
        $kategori = Kategori::all();
        return view('produk.edit', compact('produk','kategori'));
    }

    public function update(Request $request, string $id)
    {   
        $old_file = $request->old_file;
        $validatedData = $request->validate([
            'kategori'=>'required',
            'nama_produk'=>'required',
            'harga_beli'=>'required|numeric',
            'stok'=>'required|numeric',
            'file' => 'file|mimes:jpeg,png|max:100',
        ]);
        
        if ($request->hasFile('file')) {
            if ($request->old_file) {
                Storage::delete($request->old_file);
            }
            $path = $request->file('file')->store('foto_produk');
        }else{
            $path = $old_file;
        }

        $harga_beli = $request->harga_beli;
        $harga_jual = $harga_beli + ($harga_beli * 0.3);

        $produk = Produk::find($id);
        $produk->nama_produk = $request->nama_produk;
        $produk->kategori_id = $request->kategori;
        $produk->harga_beli = $request->harga_beli;
        $produk->harga_jual = $harga_jual;
        $produk->stok = $request->stok;
        $produk->image = $path;
        $produk->save();

        return redirect('produk')->with('success','Data berhasil diperbarui');
    }

    public function destroy(string $id)
    {
        Produk::where('id',$id)->delete();
        return redirect()->back()->with('success','Data berhasil dihapus');
    }
}

resources/views/produk/create.blade.php
@extends('layout.main')
@section('content')
<div class="mt-4">
    <h4 id="path">{{ Breadcrumbs::render('create') }}</h4>
</div>
    <div class="row mx-4">
        <div class="col mt-3">
            <form action="{{route('produk.store')}}" method="post" class="" enctype="multipart/form-data">
                @csrf @method('post')
                <div class="row mb-3">
                    <div class="col">
                        <label for="kategori" class="mb-2">Kategori</label>
                        <select name="kategori" class="form-select form-select @error('kategori') is-invalid @enderror" aria-label="Default select example">
                            <option selected><i class="bi bi-box-seam"></i> Pilh kategori</option>
                            @foreach ($kategori as $data)
                                <option value="{{$data->id}}">{{$data->nama_kategori}}</option>
                            @endforeach
                        </select>
                        @error('kategori')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="col">
                        <label for="nama_produk" class="mb-2">Nama Produk</label>
                        <input type="text" name="nama_produk" class="form-control @error('nama_produk') is-invalid @enderror" value="{{old('nama_produk')}}" id="" placeholder="Masukkan nama produk">
                        @error('nama_produk')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col">
                        <label for="harga_beli" class="mb-2">Harga Beli</label>
                        <input type="text" name="harga_beli" class="form-control @error('harga_beli') is-invalid @enderror" value="{{old('harga_beli')}}" placeholder="Masukkan harga beli">
                        @error('harga_beli')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="col">
                        <label for="stok" class="mb-2">Stok</label>
                        <input type="text" name="stok" class="form-control @error('stok') is-invalid @enderror" value="{{old('stok')}}" placeholder="Masukkan stok produk">
                        @error('stok')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                </div>
                <div class="drop-area @error('file') is-invalid @enderror" id="drop-area">
                    <i class="bi bi-cloud-arrow-up"></i>
                    <p id="drop-tittle">Drop file disini atau tekan untuk upload</p>
                </div>
                @error('file')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
                @enderror
                <input type="file" id="file-input" name="file" multiple hidden>
                <div class="mt-3">
                    <button type="submit" class="btn btn-danger"><i class="bi bi-plus-circle me-2"></i>Tambah</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/produk/edit.blade.php
@extends('layout.main')
@section('content')
<div class="mt-4">
    <h4 id="path">{{ Breadcrumbs::render('edit') }}</h4>
</div>
    <div class="row mx-4">
        <div class="col mt-3">
            @foreach ($produk as $data)
            <form action="{{route('produk.update',$data->id)}}" method="post" class="" enctype="multipart/form-data">
                @csrf @method('put')
                <div class="row mb-3">
                    <div class="col">
                        <label for="kategori" class="mb-2">Kategori</label>
                        <select name="kategori" class="form-select form-select" aria-label="Default select example">
                            @foreach ($kategori as $kategori)
                                <option {{$data->kategori_id == $kategori->id ? 'selected' : ''}} value="{{$kategori->id}}">{{$kategori->nama_kategori}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="col">
                        <label for="nama_produk" class="mb-2">Nama Produk</label>
                        <input type="text" name="nama_produk" value="{{$data->nama_produk}}" class="form-control @error('nama_produk') is-invalid @enderror" id="" placeholder="Masukkan nama produk">
                        @error('nama_produk')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col">
                        <label for="harga_beli" class="mb-2">Harga Beli</label>
                        <input type="text" name="harga_beli" value="{{$data->harga_beli}}" class="form-control @error('harga_beli') is-invalid @enderror" id="" placeholder="Masukkan harga beli">
                        @error('harga_beli')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <div class="col">
                        <label for="stok" class="mb-2">Stok</label>
                        <input type="text" name="stok" value="{{$data->stok}}" class="form-control @error('stok') is-invalid @enderror" id="" placeholder="Masukkan stok produk">
                        @error('stok')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                </div>
                <div>
                    <input type="hidden" name="old_file" value="{{$data->image}}">
                    <img src="{{asset('storage/'.$data->image)}}" alt="" srcset="" style="max-width: 50px">
                </div>
                <div class="drop-area" id="drop-area">
                    <i class="bi bi-cloud-arrow-up"></i>
                    <p id="drop-tittle">Drop file disini atau tekan untuk upload gambar baru</p>
                </div>
                @error('file')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
                @enderror
                <input type="file" id="file-input" name="file" multiple hidden>
                @endforeach
                <div class="mt-3">
                    <button type="submit" class="btn btn-danger"><i class="bi bi-floppy me-2"></i>Simpan</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/produk/excel.blade.php
@extends('layout.main')
@section('content')
<div class="mx-auto mt-5 text-center" style="width: 50%">
    <h5>Masukkan pengaturan untuk cetak data ke Excel</h5>
    <form action="{{route('export')}}" method="get" class=text-center mx-auto">
        <div class="row mb-3">
            <input type="text" name="cari_produk" id="" placeholder="cari produk" class="form-control">
        </div>
        <div class="row mb-3">
            <select name="kategori" class="form-select" aria-label="Default select example">
                <option selected value=""><i class="bi bi-box-seam"></i> Semua</option>
                @foreach ($kategori as $data)
                    <option value="{{$data->id}}">{{$data->nama_kategori}}</option>
                @endforeach
            </select>
        </div>
        <div class="row mb-3">
            <button type="submit" class="btn btn-success mx-1" id="btn-filter">Download</button>
        </div>
    </div>
    </form>
</div>

@endsection

resources/views/produk/index.blade.php
@extends('layout.main')
@section('content')
<div class="mt-4">
    <h4 id="path">{{ Breadcrumbs::render('produk') }}</h4>
</div>
<div class="row mt-4">
    <div class="col-8">
        <div class="row">
            <form action="" method="get" class="row row-cols-sm-auto g-1 mb-4">
                <div class="col">
                    <input type="text" name="cari_produk" id="" placeholder="cari produk" class="form-control form-control-sm">
                </div>
                <div class="col">
                    <select name="kategori" class="form-select form-select-sm" aria-label="Default select example">
                        <option selected value=""><i class="bi bi-box-seam"></i> Semua</option>
                        @foreach ($kategori as $data)
                            <option value="{{$data->id}}">{{$data->nama_kategori}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col">
                    <button type="submit" class="btn btn-danger mx-1 btn-sm" id="btn-filter">Search</button>
                    <button class="btn btn-light btn-sm" id="btn-reset">Reset</button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-4">
        <div class="row">
            <div class="col-1"></div>
            <div class="col-5">
                <a href="{{url('excel')}}" class="btn btn-success btn-sm"><i class="bi bi-filetype-xlsx"></i> Export excel</a>
            </div>
            <div class="col-6">
                <a href="{{url('produk/create')}}" class="btn btn-danger btn-sm"><i class="bi bi-plus-circle"></i> Tambah data produk</a>
            </div>
        </div>
    </div>
</div>
@if(session('success'))
    <div class="alert alert-success alert-dismissible fade show mx-auto" id="alert" role="alert">
        {{ session('success') }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
@endif
@if(session('error'))
    <div class="alert alert-danger alert-dismissible fade show mx-auto" id="alert" role="alert">
        {{ session('error') }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
@endif
<div class="mx-2">
      
@isset($produk)
<table class="table table-hover text-center">
    <thead class="table-secondary">
        <tr>
            <th>No</th>
            <th>Gambar</th>
            <th>Nama Produk</th>
            <th>Kategori</th>
            <th>Harga Beli (Rp)</th>
            <th>Harga Jual (Rp)</th>
            <th>Stok</th>
            <th colspan="2">Aksi</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($produk as $data)
        <tr>
            <td>{{$loop->iteration}}</td>
            <td><img src="{{asset('storage/'.$data->image)}}" alt="" srcset="" style="max-width: 30px" class=""></td>
            <td>{{$data->nama_produk}}</td>
            <td>{{$data->kategori->nama_kategori}}</td>
            <td>{{$data->harga_beli}}</td>
            <td>{{$data->harga_jual}}</td>
            <td>{{$data->stok}}</td>
            <td>
                <a href="{{route('produk.edit',$data->id)}}" class="btn btn-success"><i class="bi bi-pencil-fill"></i></a>
            </td>
            <td>
                <form action="{{ route('produk.destroy',$data->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger" title="Hapus data" onclick="return confirm('Apakah anda yakin ingin menghapus?')"><i class="bi bi-trash3-fill"></i></button>
                </form>
            </td>
        </tr>             
        @endforeach
    </tbody>
</table>
{{$produk->links('layout.pagination')}}
@endisset 

</div>
  
@endsection

resources/views/produk/table.blade.php
<table class="table table-hover text-center">
    <thead class="table-secondary">
        <tr>
            <th>No</th>
            {{-- <th>Gambar</th> --}}
            <th>Nama Produk</th>
            <th>Kategori</th>
            <th>Harga Beli (Rp)</th>
            <th>Harga Jual (Rp)</th>
            <th>Stok</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($item as $data)
        <tr>
            <td>{{$loop->iteration}}</td>
            {{-- <td><img src="{{asset('storage/'.$data->image)}}" alt="" srcset="" style="max-width: 30px" class=""></td> --}}
            <td>{{$data->nama_produk}}</td>
            <td>{{$data->kategori->nama_kategori}}</td>
            <td>{{$data->harga_beli}}</td>
            <td>{{$data->harga_jual}}</td>
            <td>{{$data->stok}}</td>
        </tr>             
        @endforeach
    </tbody>
</table>
 